ALTER TABLE urls
    ADD COLUMN a TEXT[] DEFAULT NULL,
    ADD COLUMN host VARCHAR(255) DEFAULT NULL,
    ADD COLUMN path VARCHAR(1024) DEFAULT NULL,
    ADD COLUMN port INTEGER DEFAULT NULL,
    ADD COLUMN tech TEXT[] DEFAULT NULL,
    ADD COLUMN response_time VARCHAR(50) DEFAULT NULL,
    ADD COLUMN input VARCHAR(255) DEFAULT NULL,
    ADD COLUMN lines INTEGER DEFAULT NULL,
    ADD COLUMN title VARCHAR(1024) DEFAULT NULL,
    ADD COLUMN words INTEGER DEFAULT NULL,
    ADD COLUMN failed BOOLEAN DEFAULT FALSE,
    ADD COLUMN method VARCHAR(10) DEFAULT NULL,
    ADD COLUMN scheme VARCHAR(50) DEFAULT NULL,
    ADD COLUMN cdn_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN cdn_type VARCHAR(255) DEFAULT NULL,
    ADD COLUMN final_url VARCHAR(1024) DEFAULT NULL,
    ADD COLUMN resolvers TEXT[] DEFAULT NULL,
    ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    ADD COLUMN webserver VARCHAR(255) DEFAULT NULL,
    ADD COLUMN status_code INTEGER DEFAULT NULL,
    ADD COLUMN content_type VARCHAR(255) DEFAULT NULL,
    ADD COLUMN content_length INTEGER DEFAULT NULL,
    ADD COLUMN chain_status_codes INTEGER[] DEFAULT NULL;

UPDATE urls SET
    a = array_remove(string_to_array(replace(replace(trim(both '[]' from httpx_data->>'a'), '"', ''), ' ', ''), ','), ''),
    host = httpx_data->>'host',
    path = httpx_data->>'path',
    port = (httpx_data->>'port')::INTEGER,
    tech = array_remove(string_to_array(replace(replace(trim(both '[]' from httpx_data->>'tech'), '"', ''), ' ', ''), ','), ''),
    response_time = httpx_data->>'time',
    input = httpx_data->>'input',
    lines = (httpx_data->>'lines')::INTEGER,
    title = httpx_data->>'title',
    words = (httpx_data->>'words')::INTEGER,
    failed = (httpx_data->>'failed')::BOOLEAN,
    method = httpx_data->>'method',
    scheme = httpx_data->>'scheme',
    cdn_name = httpx_data->>'cdn_name',
    cdn_type = httpx_data->>'cdn_type',
    final_url = httpx_data->>'final_url',
    resolvers = array_remove(string_to_array(replace(replace(trim(both '[]' from httpx_data->>'resolvers'), '"', ''), ' ', ''), ','), ''),
    timestamp = (httpx_data->>'timestamp')::TIMESTAMP WITH TIME ZONE,
    webserver = httpx_data->>'webserver',
    status_code = (httpx_data->>'status_code')::INTEGER,
    content_type = httpx_data->>'content_type',
    content_length = (httpx_data->>'content_length')::INTEGER,
    chain_status_codes = array_remove(string_to_array(replace(replace(trim(both '[]' from httpx_data->>'chain_status_codes'), '"', ''), ' ', ''), ','), '')::INTEGER[];

ALTER TABLE urls DROP COLUMN httpx_data;